.TH gtick 1 "4 January 2004" "Version 0.2.13" "GTick Manual"

.SH NAME
gtick \- A GTK+ metronome

.SH SYNOPSIS
gtick

.SH DESCRIPTION
.B GTick
is a metronome application written using the GTK+ widget set. Output is
sent to the soundcard (using direct calls to /dev/dsp) providing a reliable
timing guide.

.B GTick 
has a BPM (Beats Per Minute) scale of 30bpm to 250bpm, catering for
almost any need; and it is known to work on Linux and FreeBSD with
OSS interface.
It includes a Volume control and different meters.

.SH AUTHOR
Alex Roberts <bse@dial.pipex.com>.
DSP core rewrite, improvements and bugfixes by Roland Stigge <stigge@antcom.de>
(current maintainer).
This Manpage was initially written by Cord Beermann <Cord@Wunder-Nett.org> for
Debian.
